### ISSUE TITLE
Unable to login on ADFS account

### ISSUE THREAD

**Issue by oscarcp** [squalou/google-chat-linux#25]
(Sorry for the last issue, I pushed enter before finishing)

This is and edge case and I would understand completely if you don't want to tackle it.

In the company that I work for there is a centralized authentication service for Google Suite, every time that you login into the google account, you get redirected to the ADFS and the once you validated, you get redirected to Google, which logs you in.

In this electron app, when you make the first post into the ADFS page, it gets opened in an actual browser tab in a separate application, making authentication impossible, is there any way to fix this? Maybe it's enforced on the ADFS side, I don't know...

I attach a couple screenshots to give context:
![Screenshot from 2020-11-24 20-18-12](https://user-images.githubusercontent.com/462631/100141439-badbc500-2e92-11eb-82b7-b0227241673a.png)
Type you email and click next, you get redirected to the ADFS site inside the electron app.
![Screenshot from 2020-11-24 20-18-33](https://user-images.githubusercontent.com/462631/100141499-d050ef00-2e92-11eb-8d0e-e4a5ebf77d70.png)
Put your username and password here and click "Sign in", adn then a new tab opens in an actual web browser, which makes it impossible for the authentication to get back to the electron app

**Comment by squalou** [comment]
Hi,

you may be in luck !
It's worth a try, I fixed a similar case 2 days ago for #23 

Try this :
- make sure you use 0.5.7-4
- open the app
- hit Alt : menu appears
- in Menu choose  "Use temporary third ....." (see screenshot)
- app will restart
- try to login.

![image](https://user-images.githubusercontent.com/4623644/100152409-f1b9d700-2ea2-11eb-8996-e4a709c55041.png)


If it works : that's cool !
You can revert to regular use using the ame method (Alt -> Menu).
You should stay logged in for around one month, it all depends on security configuration of your auth provider. ... and then you would need to repeat the operation each time.


Note the side effects : this "temporary mode" makes
- all url open in the app itslef instead of browser
- systray coor changes does not work

Let me know the results.

Finally : in case nothing of this works, you can give a try at Ferdi (https://getferdi.com/), it's a multi-service client taht also supports google chat. A bit more heavy, but may work in your case.

**Comment by oscarcp** [comment]
I just tried it and it works perfectly! thanks! I'm closing the ticket as well

**Comment by squalou** [comment]
Great to here this !

in the future I'll probably add this to the 'systray menu' too, to make it easier to reach.
