### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by vincenzocaselli** [squalou/google-chat-linux#7]
Hi,
first of all: compliments for the great work!!
I just updated from AUR and saw that now it is possible to open the browser on a meet by double clicking the meet on the chat (before it wasn't possible); great!!
Is there a roadmap for the Autostart feature in the settings (now I copy manually the script for autostart) ?
Thank you very much!!!!!
Vincenzo

**Comment by squalou** [comment]
Hi,

thank you !

Good news : honestly the meet thing is a good surprise,  side effect of other changes (not all are cool, sadly, especially the icon color in systray can no more be changed)

I never thought about adding autostart, simply because supporting all flavours of all WMs and distributions is not exaclty appealing.

Copy/paste in autostart is what I do for xfce :)

I don't intend to do anything more, feel free to contribute if you ever know more about this subject.
